version: '3.8'

services:
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - express

  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: express_api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdatabase
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: yourdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
